#!/usr/bin/env bash

master=$(cat ~/master.key)
site=$(recsel -t Password -s $master -P Resource ~/.local/var/lib/pf/passwords.rec | sort | uniq | fzf)

echo "Password for..."
recsel -t Password -s $master -e "Resource = \"$site\"" -p Resource,Id ~/.local/var/lib/pf/passwords.rec

recsel -t Password -s $master -P Password ~/.local/var/lib/pf/passwords.rec -e "Resource = \"$site\"" | xsel --clipboard
echo "Stored in the clipboard"
